# Generated by Django 3.1 on 2022-10-17 18:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0002_auto_20221017_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sno',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.print, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default="My Freakin' Awesome Blog!"),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default="My Freakin' Awesome Blog!", max_length=225),
        ),
    ]
