# Generated by Django 3.1 on 2022-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0006_auto_20221018_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
