# Generated by Django 3.1 on 2022-10-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0013_auto_20221020_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
