# Generated by Django 3.1 on 2022-10-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0014_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Hello', max_length=255),
        ),
    ]
