# Generated by Django 3.1 on 2022-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0017_auto_20221020_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='{{request.user.username}}', max_length=13),
        ),
    ]
