# Generated by Django 3.1 on 2022-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0018_auto_20221020_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=13),
        ),
    ]
