# Generated by Django 3.1 on 2022-10-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0019_auto_20221020_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(),
        ),
    ]
