# Generated by Django 3.1 on 2022-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0022_auto_20221021_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
    ]
