# Generated by Django 3.1 on 2022-10-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0024_post_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
