# Generated by Django 3.1 on 2022-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0028_auto_20221022_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='post.username', max_length=255),
        ),
    ]
