# Generated by Django 3.1 on 2022-10-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0029_auto_20221022_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
