# Generated by Django 3.1 on 2022-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0030_auto_20221022_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
