# Generated by Django 3.1 on 2022-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0036_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
